# This is a basic workflow to help you get started with Actions

name: CI

# Schedule the run
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
    # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install python-csv

      # Parse them all
      - name: Scrape
        run: |
          python script.py
          
      # Commit & Push
      - name: Commit a new report
        run: |
            mkdir data
            cp data/* data
            git config --global user.name 'GitHub Actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -am "Add new"
            git push
        env:
          TZ: Europe/Rome
